/**
 * Typed access to the catalogue of public ISS Live symbols.
 *
 * The JSON is generated by `npm run build:catalog` from data/PUIList.xml.
 * Do not edit pui-catalog.json by hand: regenerate it.
 */
import catalogJson from './pui-catalog.json'

export interface PuiSymbol {
  /** Identifier to subscribe to on Lightstreamer (e.g. "USLAB000058"). */
  pui: string
  /** The mission control console that monitors this parameter (ETHOS, SPARTAN, ADCO…). */
  discipline: string
  /** Original description, in English, as published by NASA. */
  description: string
  /** Unit declared in the 2011 catalogue — often wrong, see telemetry/units.ts. */
  units: string | null
  opsNom: string | null
  engNom: string | null
  min: string | null
  max: string | null
  /** Decoding table for state parameters (e.g. { "1": "PROCESS", "2": "STANDBY" }). */
  values: Record<string, string> | null
  /** Number of decimals published by the source, where it states one. */
  precision: number | null
}

export interface PuiCatalog {
  source: string
  sourceCreated: string | null
  generatedAt: string
  disciplines: string[]
  symbols: PuiSymbol[]
}

export const catalog = catalogJson as PuiCatalog

const bySymbol = new Map<string, PuiSymbol>(catalog.symbols.map((symbol) => [symbol.pui, symbol]))

export function getSymbol(pui: string): PuiSymbol | undefined {
  return bySymbol.get(pui)
}

export function symbolsOfDiscipline(discipline: string): PuiSymbol[] {
  return catalog.symbols.filter((symbol) => symbol.discipline === discipline)
}

/** Composite disciplines ("SPARTAN/VVO") belong to each of their consoles. */
export function disciplineParts(discipline: string): string[] {
  return discipline.split('/')
}
